### ISSUE TITLE
copy_field with nested array and `*`-array wildcard does not work

### ISSUE THREAD

**Issue by TobiasNx** [metafacture/metafacture-fix#155]
```
set_array("Test_1[]")
set_array("Test_2[]")
copy_field("animals[].*.B[].*", "Test_1[].$append")
copy_field("animals[].*.A[].*.name", "Test_2[].$append")
```
Results in:
``` 
"Test_1" : [ ],
  "Test_2" : [ ]
```
Expected:
``` 
"Test_1" : [ "Jake", "Blacky"],
  "Test_2" : [ "First", "Second"]
```

I do not know if this is an issue of multiple asterisks `*` or if this is related to #148. I also do not know if this is an issue for more than jus copy_field.

[See playground](https://metafacture.org/playground/?flux=PG_DATA%0A%7Cas-records%0A%7C+decode-json%0A%7C+fix%0A%7C+encode-json%28prettyPrinting%3D%22true%22%29%0A%7C+print%0A%3B&fix=set_array%28%22Test_1%5B%5D%22%29%0Aset_array%28%22Test_2%5B%5D%22%29%0Acopy_field%28%22animals%5B%5D.%2A.A%5B%5D.%2A.name%22%2C+%22Test_1%5B%5D.%24append%22%29+%0Acopy_field%28%22animals%5B%5D.%2A.B%5B%5D.%2A%22%2C+%22Test_2%5B%5D.%24append%22%29+&data=%7B%0A%09%22animals%22%3A+%5B%0A%09%09%7B%0A%09%09%09%22A%22%3A+%5B%7B%22name%22%3A%22Jake%22%7D%5D%2C%0A%09%09%09%22B%22%3A+%5B%22First%22%5D%0A%09%09%09%0A%09%09%7D%2C%0A%09%09%7B%0A%09%09%09%22A%22%3A+%5B%7B%22name%22%3A%22Blacky%22%7D%5D%2C%0A%09%09%09%22B%22%3A+%5B%22Second%22%5D%0A%09%09%7D%0A%09%5D%0A%7D&active-editor=fix)

Testcase here:
https://github.com/TobiasNx/fix-FunctionalReview-Testing/commit/161a676af2a4562f92b4847be480475fd43cfe30

**Comment by fsteeg** [comment]
Add as integration test in https://github.com/metafacture/metafacture-fix/issues/160 / revisit after https://github.com/metafacture/metafacture-fix/issues/102.

**Comment by fsteeg** [comment]
I think this is fixed in master, [see playground](https://metafacture.org/playground/?flux=PG_DATA%0A%7Cas-records%0A%7C+decode-json%0A%7C+fix%0A%7C+encode-json%28prettyPrinting%3D%22true%22%29%0A%7C+print%0A%3B&fix=set_array%28%22Test_1%5B%5D%22%29%0Aset_array%28%22Test_2%5B%5D%22%29%0Acopy_field%28%22animals%5B%5D.%2A.A%5B%5D.%2A.name%22%2C+%22Test_1%5B%5D.%24append%22%29+%0Acopy_field%28%22animals%5B%5D.%2A.B%5B%5D.%2A%22%2C+%22Test_2%5B%5D.%24append%22%29+&data=%7B%0A%09%22animals%22%3A+%5B%0A%09%09%7B%0A%09%09%09%22A%22%3A+%5B%7B%22name%22%3A%22Jake%22%7D%5D%2C%0A%09%09%09%22B%22%3A+%5B%22First%22%5D%0A%09%09%09%0A%09%09%7D%2C%0A%09%09%7B%0A%09%09%09%22A%22%3A+%5B%7B%22name%22%3A%22Blacky%22%7D%5D%2C%0A%09%09%09%22B%22%3A+%5B%22Second%22%5D%0A%09%09%7D%0A%09%5D%0A%7D&active-editor=fix) and passing [integration test](https://github.com/metafacture/metafacture-fix/tree/master/metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/copy_fieldFromArrayOfStringsInArrayOfObjectsWithAsterisk). Please reopen if not.
