### ISSUE TITLE
`replace_all` with asterisk with optional subfield creates new subfield

### ISSUE THREAD

**Issue by TobiasNx** [metafacture/metafacture-fix#377]
See: https://github.com/metafacture/metafacture-fix/pull/376

https://github.com/metafacture/metafacture-fix/tree/d18a5035d2b74508d685ec863c91e4382aff2c26/metafix/src/test/resources/org/metafacture/metafix/integration/method/fromXml/toJson/replace_allInOptionalSubfieldOfRepeatedObjectsWithAsterisk

in:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<collection xmlns="http://www.loc.gov/MARC21/slim">
    <record>
        <datafield tag="650" ind1=" " ind2=" ">
            <subfield code="a">Nonprofit organizations</subfield>
            <subfield code="x">Management.</subfield>
        </datafield>
        <datafield tag="650" ind1=" " ind2=" ">
            <subfield code="a">Nonprofit organizations</subfield>
            <subfield code="x">Management</subfield>
            <subfield code="v">Case studies.</subfield>
        </datafield>
    </record>
</collection>
```

```perl
do list(path: "650??", "var": "$i")
  copy_field("$i.a", "RSWK[].$append.subjectTopicName")
  copy_field("$i.v", "RSWK[].$last.subjectGenre")
end
replace_all("RSWK[].*.subjectGenre", "[.]$", "")
retain("RSWK[]")
```

Out:
```json
{
  "RSWK" : [ {
    "subjectTopicName" : "Nonprofit organizations",
    "subjectGenre" : "Case studies"
  }, {
    "subjectTopicName" : "Nonprofit organizations",
    "subjectGenre" : "Case studies."
  } ]
}
```

Expected:

```json
{
  "RSWK" : [ {
    "subjectTopicName" : "Nonprofit organizations"
  }, {
    "subjectTopicName" : "Nonprofit organizations",
    "subjectGenre" : "Case studies"
  } ]
}
```

**Comment by TobiasNx** [comment]
When using set_array this seems to work. Not sure why:

```
set_array("RSWK[]")
do list(path: "650??", "var": "$i")
  copy_field("$i.a", "RSWK[].$append.subjectTopicName")
  copy_field("$i.v", "RSWK[].$last.subjectGenre")
end
replace_all("RSWK[].*.subjectGenre", "[.]$", "")
retain("RSWK[]")
```

**Comment by blackwinter** [comment]
It seems to be caused by `copy_field` carrying over the _old_ value's path (`650  .v`) to the _new_ location (`RSWK[].$last.subjectGenre`). That way, `replace_all` gets confused and _assumes_ that the target position for the transformed value must be the _first_ array element.

It can be solved by explicitly telling `copy_field` (and other call sites in the same vein) to ignore the old value's path (`.withPathSet(null)`; see #380). But I'm unsure whether this is the right approach; at the very least, it _modifies_ the original value's path which might cause subsequent issues down the line.

I'm sorry to say this, but our path handling is quite a mess ;)
