### ISSUE TITLE
Add fix-filter functionality

### ISSUE THREAD

**Issue by fsteeg** [metafacture/metafacture-fix#40]
Like the `Filter` Java class / `filter` Flux command for a Morph file, we want `MetafixFilter` / `fix-filter` to filter records based on a Fix file. Required for https://gitlab.com/oersi/oersi-etl/-/issues/28.

**Comment by blackwinter** [comment]
Removed again in #60:

---

My idea was that we don't need a separate filter command with fix, since we can filter in the main fix (or in a separate fix, but with normal fix behavior), [e.g. like this](https://github.com/metafacture/metafacture-fix/blob/e4dec3aef20ed025150f43cea4fe7cba582f6a0d/org.metafacture.fix/src/test/java/org/metafacture/metafix/MetafixRecordTest.java#L611).

_Originally posted by @fsteeg in https://github.com/metafacture/metafacture-fix/issues/60#issuecomment-961885487_
