### ISSUE TITLE
Create a Record class that wraps the `Map<String, Object>`

### ISSUE THREAD

**Issue by fsteeg** [metafacture/metafacture-fix#64]
Came up in https://github.com/metafacture/metafacture-fix/pull/60#pullrequestreview-791798200.

**Comment by blackwinter** [comment]
Copying previous discussion for better overview:

---

I would suggest to create a `Record` class that wraps the `Map<String, Object>` instead of "littering" `Metafix` and `FixMethod` with static methods. But that can happen later. (Maybe it would be an opportunity for me to get more acquainted with the new code.)

_Originally posted by @blackwinter in https://github.com/metafacture/metafacture-fix/pull/60#pullrequestreview-791798200_

**Comment by fsteeg** [comment]
No functional review (refactoring), code review: @fsteeg
