### ISSUE TITLE
Make the full record available in binds

### ISSUE THREAD

**Issue by fsteeg** [metafacture/metafacture-fix#66]
See https://github.com/metafacture/metafacture-fix/pull/60#pullrequestreview-795591354.

Functional review: @TobiasNx
Code review: @blackwinter

**Comment by blackwinter** [comment]
Copying previous discussion for better overview:

---

This prevents access to the actual record. Is this intentional?

_Originally posted by @blackwinter in https://github.com/metafacture/metafacture-fix/pull/60#discussion_r741215149_

---

My idea was that in the scope of the bind, the record (as the subexpressions see it) should only contain the bound value. I'm not sure why though, that might very well make no sense.

_Originally posted by @fsteeg in https://github.com/metafacture/metafacture-fix/pull/60#discussion_r743702989_

---

I wasn't able to find it documented anywhere, but Catmandu seems to preserve access to the whole record:

```perl
$fixes = <<EOF;
do list(path:foo,var:loop)
  copy_field(test,loop.baz)
end
EOF

$fixer = Catmandu::Fix->new(fixes => [$fixes]);

is_deeply $fixer->fix({foo => [{bar => 1}, {bar => 2}], test => 42}),
    {foo => [{bar => 1, baz => 42}, {bar => 2, baz => 42}], test => 42},
    'binding scope testing';
```

_Originally posted by @blackwinter in https://github.com/metafacture/metafacture-fix/pull/60#discussion_r743730670_

---

I agree, the full record should be available. I've opened https://github.com/metafacture/metafacture-fix/issues/66 since this does require some work that I probably won't have time to do this week (simply using the full record with the current implementation results in overwriting previous values under the same key, which is covered by a test).

_Originally posted by @fsteeg in https://github.com/metafacture/metafacture-fix/pull/60#discussion_r744725815_

**Comment by blackwinter** [comment]
Catmandu's behaviour seems to [depend on the presence of the `var` option](https://github.com/hbz/Catmandu/blob/bb54964/lib/Catmandu/Fix/Bind/list.pm#L47):

```perl
$fixes = <<EOF;
do list(path:foo)
  copy_field(test,baz)
end
EOF

$fixer = Catmandu::Fix->new(fixes => [$fixes]);

is_deeply $fixer->fix({foo => [{bar => 1}, {bar => 2}], test => 42}),
    {foo => [{bar => 1}, {bar => 2}], test => 42},
    'binding scope w/o var testing';
```

See also hbz/Catmandu@22d7359.

**Comment by fsteeg** [comment]
Deployed to test: [access outer `type` from inside the bind](https://test.metafacture.org/playground/?data=1%7Btype%3A+book%2C+name%3A+Faust%7D%0A2%7Btype%3A+journal%2C+name%3A+Nature%7D&flux=PG_DATA%0A%7Cas-lines%0A%7Cdecode-formeta%0A%7Cfix%0A%7Cencode-json%28prettyPrinting%3D%22true%22%29%0A%7Cprint%0A%3B&fix=do+list%28%27path%27%3A+%27name%27%2C+%27var%27%3A+%27n%27%29%0A+if+any_equal%28%27type%27%2C%27book%27%29%0A++paste%28%27title%27%2C%27~Book%3A%27%2C%27n%27%29%0A+else%0A++paste%28%27title%27%2C%27~Journal%3A%27%2C%27n%27%29%0A+end%0Aend%0Aretain%28%27title%27%29&morph=%3C%3Fxml+version%3D%221.0%22+encoding%3D%22UTF-8%22%3F%3E%0A%3Cmetamorph+xmlns%3D%22http%3A//www.culturegraph.org/metamorph%22+xmlns%3Axsi%3D%22http%3A//www.w3.org/2001/XMLSchema-instance%22%0A%09version%3D%221%22%3E%0A%09%3Crules%3E%0A%09%09%3Cdata+source%3D%22_id%22+name%3D%22id%22/%3E%0A%09%09%3Cdata+source%3D%22a%22+name%3D%22title%22/%3E%0A%09%09%3Ccombine+value%3D%22%24%7Bfirst%7D+%24%7Blast%7D+aus+%24%7Bplace%7D%22+name%3D%22author%22%3E%0A%09%09%09%3Cdata+source%3D%22b.v%22+name%3D%22first%22+/%3E%0A%09%09%09%3Cdata+source%3D%22b.n%22+name%3D%22last%22+/%3E%0A%09%09%09%3Cdata+source%3D%22c%22+name%3D%22place%22+/%3E%0A%09%09%3C/combine%3E%0A%09%3C/rules%3E%0A%3C/metamorph%3E%0A&active-editor=fix) ([see issue on prod](https://metafacture.org/playground/?data=1%7Btype%3A+book%2C+name%3A+Faust%7D%0A2%7Btype%3A+journal%2C+name%3A+Nature%7D&flux=PG_DATA%0A%7Cas-lines%0A%7Cdecode-formeta%0A%7Cfix%0A%7Cencode-json%28prettyPrinting%3D%22true%22%29%0A%7Cprint%0A%3B&fix=do+list%28%27path%27%3A+%27name%27%2C+%27var%27%3A+%27n%27%29%0A+if+any_equal%28%27type%27%2C%27book%27%29%0A++paste%28%27title%27%2C%27~Book%3A%27%2C%27n%27%29%0A+else%0A++paste%28%27title%27%2C%27~Journal%3A%27%2C%27n%27%29%0A+end%0Aend%0Aretain%28%27title%27%29&morph=%3C%3Fxml+version%3D%221.0%22+encoding%3D%22UTF-8%22%3F%3E%0A%3Cmetamorph+xmlns%3D%22http%3A//www.culturegraph.org/metamorph%22+xmlns%3Axsi%3D%22http%3A//www.w3.org/2001/XMLSchema-instance%22%0A%09version%3D%221%22%3E%0A%09%3Crules%3E%0A%09%09%3Cdata+source%3D%22_id%22+name%3D%22id%22/%3E%0A%09%09%3Cdata+source%3D%22a%22+name%3D%22title%22/%3E%0A%09%09%3Ccombine+value%3D%22%24%7Bfirst%7D+%24%7Blast%7D+aus+%24%7Bplace%7D%22+name%3D%22author%22%3E%0A%09%09%09%3Cdata+source%3D%22b.v%22+name%3D%22first%22+/%3E%0A%09%09%09%3Cdata+source%3D%22b.n%22+name%3D%22last%22+/%3E%0A%09%09%09%3Cdata+source%3D%22c%22+name%3D%22place%22+/%3E%0A%09%09%3C/combine%3E%0A%09%3C/rules%3E%0A%3C/metamorph%3E%0A&active-editor=fix)).

**Comment by TobiasNx** [comment]
> Deployed to test: [access outer `type` from inside the bind](https://test.metafacture.org/playground/?data=1%7Btype%3A+book%2C+name%3A+Faust%7D%0A2%7Btype%3A+journal%2C+name%3A+Nature%7D&flux=PG_DATA%0A%7Cas-lines%0A%7Cdecode-formeta%0A%7Cfix%0A%7Cencode-json%28prettyPrinting%3D%22true%22%29%0A%7Cprint%0A%3B&fix=do+list%28%27path%27%3A+%27name%27%2C+%27var%27%3A+%27n%27%29%0A+if+any_equal%28%27type%27%2C%27book%27%29%0A++paste%28%27title%27%2C%27~Book%3A%27%2C%27n%27%29%0A+else%0A++paste%28%27title%27%2C%27~Journal%3A%27%2C%27n%27%29%0A+end%0Aend%0Aretain%28%27title%27%29&morph=%3C%3Fxml+version%3D%221.0%22+encoding%3D%22UTF-8%22%3F%3E%0A%3Cmetamorph+xmlns%3D%22http%3A//www.culturegraph.org/metamorph%22+xmlns%3Axsi%3D%22http%3A//www.w3.org/2001/XMLSchema-instance%22%0A%09version%3D%221%22%3E%0A%09%3Crules%3E%0A%09%09%3Cdata+source%3D%22_id%22+name%3D%22id%22/%3E%0A%09%09%3Cdata+source%3D%22a%22+name%3D%22title%22/%3E%0A%09%09%3Ccombine+value%3D%22%24%7Bfirst%7D+%24%7Blast%7D+aus+%24%7Bplace%7D%22+name%3D%22author%22%3E%0A%09%09%09%3Cdata+source%3D%22b.v%22+name%3D%22first%22+/%3E%0A%09%09%09%3Cdata+source%3D%22b.n%22+name%3D%22last%22+/%3E%0A%09%09%09%3Cdata+source%3D%22c%22+name%3D%22place%22+/%3E%0A%09%09%3C/combine%3E%0A%09%3C/rules%3E%0A%3C/metamorph%3E%0A&active-editor=fix) ([see issue on prod](https://metafacture.org/playground/?data=1%7Btype%3A+book%2C+name%3A+Faust%7D%0A2%7Btype%3A+journal%2C+name%3A+Nature%7D&flux=PG_DATA%0A%7Cas-lines%0A%7Cdecode-formeta%0A%7Cfix%0A%7Cencode-json%28prettyPrinting%3D%22true%22%29%0A%7Cprint%0A%3B&fix=do+list%28%27path%27%3A+%27name%27%2C+%27var%27%3A+%27n%27%29%0A+if+any_equal%28%27type%27%2C%27book%27%29%0A++paste%28%27title%27%2C%27~Book%3A%27%2C%27n%27%29%0A+else%0A++paste%28%27title%27%2C%27~Journal%3A%27%2C%27n%27%29%0A+end%0Aend%0Aretain%28%27title%27%29&morph=%3C%3Fxml+version%3D%221.0%22+encoding%3D%22UTF-8%22%3F%3E%0A%3Cmetamorph+xmlns%3D%22http%3A//www.culturegraph.org/metamorph%22+xmlns%3Axsi%3D%22http%3A//www.w3.org/2001/XMLSchema-instance%22%0A%09version%3D%221%22%3E%0A%09%3Crules%3E%0A%09%09%3Cdata+source%3D%22_id%22+name%3D%22id%22/%3E%0A%09%09%3Cdata+source%3D%22a%22+name%3D%22title%22/%3E%0A%09%09%3Ccombine+value%3D%22%24%7Bfirst%7D+%24%7Blast%7D+aus+%24%7Bplace%7D%22+name%3D%22author%22%3E%0A%09%09%09%3Cdata+source%3D%22b.v%22+name%3D%22first%22+/%3E%0A%09%09%09%3Cdata+source%3D%22b.n%22+name%3D%22last%22+/%3E%0A%09%09%09%3Cdata+source%3D%22c%22+name%3D%22place%22+/%3E%0A%09%09%3C/combine%3E%0A%09%3C/rules%3E%0A%3C/metamorph%3E%0A&active-editor=fix)).

The test-example uses a do list-bind with an non list field is this right? 

Catmandu does only iterate with an do list only over lists:

```bash
# List over all items in demo and add a foo => bar field
# { demo => [{},{},{}] } => { demo => [{foo=>bar},{foo=>bar},{foo=>bar}]}
do list(path: demo)
  add_field(foo,bar)
end
```
Source: http://librecat.org/Catmandu/#fixes-cheat-sheet

**Comment by TobiasNx** [comment]
The example should be something like that:
[See here](https://metafacture.org/playground/?data=1%7Btype%3A+book%2C+resource+%7Bname%3A+Faust%2C+language%3A+german%7D%2C+resource+%7Bname%3A+Fausto%2C+language%3A+spanish%7D+%7D%0A2%7Btype%3A+journal%2C+resource+%7Bname%3A+Nature%2C+language%3A+german%7D%2C+resource+%7Bname%3A+Nature%2C+language%3A+spanish%7D+%7D&flux=PG_DATA%0A%7Cas-lines%0A%7Cdecode-formeta%0A%7Cfix%0A%7Cencode-json%28prettyPrinting%3D%22true%22%29%0A%7Cprint%0A%3B&fix=do+list%28%27path%27%3A+%27resource%27%2C+%27var%27%3A+%27n%27%29%0A+if+all_equal%28%27type%27%2C%27book%27%29%0A++paste%28%27title%5B%5D%27%2C%27~Book%3A%27%2C%27n.name%27%29%0A+else%0A++paste%28%27title%5B%5D%27%2C%27~Journal%3A%27%2C%27n.name%27%29%0A+end%0Aend%0A&morph=%3C%3Fxml+version%3D%221.0%22+encoding%3D%22UTF-8%22%3F%3E%0A%3Cmetamorph+xmlns%3D%22http%3A//www.culturegraph.org/metamorph%22+xmlns%3Axsi%3D%22http%3A//www.w3.org/2001/XMLSchema-instance%22%0A%09version%3D%221%22%3E%0A%09%3Crules%3E%0A%09%09%3Cdata+source%3D%22_id%22+name%3D%22id%22/%3E%0A%09%09%3Cdata+source%3D%22a%22+name%3D%22title%22/%3E%0A%09%09%3Ccombine+value%3D%22%24%7Bfirst%7D+%24%7Blast%7D+aus+%24%7Bplace%7D%22+name%3D%22author%22%3E%0A%09%09%09%3Cdata+source%3D%22b.v%22+name%3D%22first%22+/%3E%0A%09%09%09%3Cdata+source%3D%22b.n%22+name%3D%22last%22+/%3E%0A%09%09%09%3Cdata+source%3D%22c%22+name%3D%22place%22+/%3E%0A%09%09%3C/combine%3E%0A%09%3C/rules%3E%0A%3C/metamorph%3E%0A&active-editor=fix)

**Comment by TobiasNx** [comment]
PS:
I have to correct myself. They are processed correctly since record is a list but has no array sign.

But it shows that the handling of repeated fields as arrays coming out of fix is not understood properly by the encoders yet. If turning it into xml it looks like this: [here](https://test.metafacture.org/playground/?data=1%7Btype%3A+book%2C+resource+%7Bname%3A+Faust%2C+language%3A+german%7D%2C+resource+%7Bname%3A+Fausto%2C+language%3A+spanish%7D+%7D%0A2%7Btype%3A+journal%2C+resource+%7Bname%3A+Nature%2C+language%3A+german%7D%2C+resource+%7Bname%3A+Nature%2C+language%3A+spanish%7D+%7D&flux=PG_DATA%0A%7Cas-lines%0A%7Cdecode-formeta%0A%7Cfix%0A%7Cencode-json%28prettyPrinting%3D%22true%22%29%0A%7Cprint%0A%3B&fix=do+list%28%27path%27%3A+%27resource%27%2C+%27var%27%3A+%27n%27%29%0A+if+all_equal%28%27type%27%2C%27book%27%29%0A++paste%28%27title%5B%5D%27%2C%27~Book%3A%27%2C%27n.name%27%29%0A+else%0A++paste%28%27title%5B%5D%27%2C%27~Journal%3A%27%2C%27n.name%27%29%0A+end%0Aend%0A&morph=%3C%3Fxml+version%3D%221.0%22+encoding%3D%22UTF-8%22%3F%3E%0A%3Cmetamorph+xmlns%3D%22http%3A//www.culturegraph.org/metamorph%22+xmlns%3Axsi%3D%22http%3A//www.w3.org/2001/XMLSchema-instance%22%0A%09version%3D%221%22%3E%0A%09%3Crules%3E%0A%09%09%3Cdata+source%3D%22_id%22+name%3D%22id%22/%3E%0A%09%09%3Cdata+source%3D%22a%22+name%3D%22title%22/%3E%0A%09%09%3Ccombine+value%3D%22%24%7Bfirst%7D+%24%7Blast%7D+aus+%24%7Bplace%7D%22+name%3D%22author%22%3E%0A%09%09%09%3Cdata+source%3D%22b.v%22+name%3D%22first%22+/%3E%0A%09%09%09%3Cdata+source%3D%22b.n%22+name%3D%22last%22+/%3E%0A%09%09%09%3Cdata+source%3D%22c%22+name%3D%22place%22+/%3E%0A%09%09%3C/combine%3E%0A%09%3C/rules%3E%0A%3C/metamorph%3E%0A&active-editor=fix)

It also shows that in FIX fields with the same name are overwritten and the last instance of this fields is passed on. In our case since `"title[]"` is not created as array but as simple field only the last instance `title[]": "Book: Fausto` is taken up.

**Comment by fsteeg** [comment]
To stay focused on the scope issue, here is an example with repeated fields:

See [fix on test](https://test.metafacture.org/playground/?data=1%7Btype%3A+book%2C+name%3A+Faust%2C+name%3A+Dune%7D%0A2%7Btype%3A+journal%2C+name%3A+Nature%2C+name%3A+Science%7D&flux=PG_DATA%0A%7Cas-lines%0A%7Cdecode-formeta%0A%7Cfix%0A%7Cencode-json%28prettyPrinting%3D%22true%22%29%0A%7Cprint%0A%3B&fix=do+list%28%27path%27%3A+%27name%27%2C+%27var%27%3A+%27n%27%29%0A+if+all_equal%28%27type%27%2C+%27book%27%29%0A++upcase%28%27n%27%29%0A+end%0A+copy_field%28%27n%27%2C%27title%5B%5D%27%29%0Aend%0Aretain%28%27title%5B%5D%27%29&morph=%3C%3Fxml+version%3D%221.0%22+encoding%3D%22UTF-8%22%3F%3E%0A%3Cmetamorph+xmlns%3D%22http%3A//www.culturegraph.org/metamorph%22+xmlns%3Axsi%3D%22http%3A//www.w3.org/2001/XMLSchema-instance%22%0A%09version%3D%221%22%3E%0A%09%3Crules%3E%0A%09%09%3Cdata+source%3D%22_id%22+name%3D%22id%22/%3E%0A%09%09%3Cdata+source%3D%22a%22+name%3D%22title%22/%3E%0A%09%09%3Ccombine+value%3D%22%24%7Bfirst%7D+%24%7Blast%7D+aus+%24%7Bplace%7D%22+name%3D%22author%22%3E%0A%09%09%09%3Cdata+source%3D%22b.v%22+name%3D%22first%22+/%3E%0A%09%09%09%3Cdata+source%3D%22b.n%22+name%3D%22last%22+/%3E%0A%09%09%09%3Cdata+source%3D%22c%22+name%3D%22place%22+/%3E%0A%09%09%3C/combine%3E%0A%09%3C/rules%3E%0A%3C/metamorph%3E%0A&active-editor=fix), compare issue [on prod](https://metafacture.org/playground/?data=1%7Btype%3A+book%2C+name%3A+Faust%2C+name%3A+Dune%7D%0A2%7Btype%3A+journal%2C+name%3A+Nature%2C+name%3A+Science%7D&flux=PG_DATA%0A%7Cas-lines%0A%7Cdecode-formeta%0A%7Cfix%0A%7Cencode-json%28prettyPrinting%3D%22true%22%29%0A%7Cprint%0A%3B&fix=do+list%28%27path%27%3A+%27name%27%2C+%27var%27%3A+%27n%27%29%0A+if+all_equal%28%27type%27%2C+%27book%27%29%0A++upcase%28%27n%27%29%0A+end%0A+copy_field%28%27n%27%2C%27title%5B%5D%27%29%0Aend%0Aretain%28%27title%5B%5D%27%29&morph=%3C%3Fxml+version%3D%221.0%22+encoding%3D%22UTF-8%22%3F%3E%0A%3Cmetamorph+xmlns%3D%22http%3A//www.culturegraph.org/metamorph%22+xmlns%3Axsi%3D%22http%3A//www.w3.org/2001/XMLSchema-instance%22%0A%09version%3D%221%22%3E%0A%09%3Crules%3E%0A%09%09%3Cdata+source%3D%22_id%22+name%3D%22id%22/%3E%0A%09%09%3Cdata+source%3D%22a%22+name%3D%22title%22/%3E%0A%09%09%3Ccombine+value%3D%22%24%7Bfirst%7D+%24%7Blast%7D+aus+%24%7Bplace%7D%22+name%3D%22author%22%3E%0A%09%09%09%3Cdata+source%3D%22b.v%22+name%3D%22first%22+/%3E%0A%09%09%09%3Cdata+source%3D%22b.n%22+name%3D%22last%22+/%3E%0A%09%09%09%3Cdata+source%3D%22c%22+name%3D%22place%22+/%3E%0A%09%09%3C/combine%3E%0A%09%3C/rules%3E%0A%3C/metamorph%3E%0A&active-editor=fix).

(The issues you mention seem to be related to #80 and #82.)

**Comment by TobiasNx** [comment]
+ 1 seems to work.

PS: Should I open another ticket concerning that non array fields should not work with list-binds?

**Comment by fsteeg** [comment]
> Should I open another ticket concerning that non array fields should not work with list-binds?

I think we should have a uniform way to process fields that may or may not be repeated. How do you iterate over the values of a field that may or may not be repeated in Catmandu?

**Comment by TobiasNx** [comment]
> > Should I open another ticket concerning that non array fields should not work with list-binds?
> 
> I think we should have a uniform way to process fields that may or may not be repeated. How do you iterate over the values of a field that may or may not be repeated in Catmandu?

I think there is no such function in catmandu but we could ask somebody of the Catmandu-Team. Or open a ticket at their repo.
