### ISSUE TITLE
Array handling with and without set_array

### ISSUE THREAD

**Issue by TobiasNx** [metafacture/metafacture-fix#80]
It seems that fix can only create arrays of objects, if with `set_array` the target array is created or it already exists.

If one only creates an array by `copy_field("sourc_field", "target.$append.field")`

The example are taken from but look at the playground to explore:
https://gitlab.com/oersi/oersi-etl/-/commit/3c3bb1cdb907b631c9848f245d8ca71aa45c17b2

connected to: #78 and #65

Without `set_array` it seems to handle newly created arrays as list of values but not of objects.

_______with` set_array`[ See example also in the playground
](https://test.metafacture.org/playground/?data=&flux=%22https%3A//gitlab.com/oersi/oersi-etl/-/raw/metafix/data/experimental/duepub-metafacture.xml%22%0A%7C+open-http%0A%7C+decode-xml%0A%7C+handle-generic-xml%28emitNamespace%3D%22true%22%29%0A%7C+fix%0A%7C+encode-json%28prettyPrinting%3D%22true%22%29%0A%7C+print%0A%3B&fix=if+any_equal+%28%22header.status%22%2C+%22deleted%22%29%0A++++reject%28%29%0Aend%0A%0A%0A%23++------------creator------------------------------------%0Aset_array%28%22creator%5B%5D%22%29%0Ado+list%28%22path%22%3A%22metadata.mods%3Amods.mods%3Aname%22%2C%22var%22%3A%22name%22%29%0A++++if+any_match%28%22name.mods%3Arole.mods%3AroleTerm.%2A.value%22%2C%22aut%7Ccre%22%29%0A++++++++copy_field%28%22name.mods%3AdisplayForm.value%22%2C%22creator%5B%5D.%24append.name%22%29%0A++++++++if+any_equal%28%22name.type%22%2C%22personal%22%29%0A++++++++++++add_field%28%22creator%5B%5D.%24last.type%22%2C+%22Person%22%29%0A++++++++end%0A++++++++if+any_equal%28%22name.type%22%2C%22corporate%22%29%0A++++++++++++add_field%28%22creator%5B%5D.%24last.type%22%2C+%22Organization%22%29%0A++++++++end%0A++++end%0Aend%0A%0Aretain%28%22creator%5B%5D%22%29&morph=&active-editor=morph)
```
#  ------------creator------------------------------------
set_array("creator[]")
do list("path":"metadata.mods:mods.mods:name","var":"name")
    if any_match("name.mods:role.mods:roleTerm.*.value","aut|cre")
        copy_field("name.mods:displayForm.value","creator[].$append.name")
        /* This seems not to work */
        if any_equal("name.type","personal") /* TODO: looks at all names, not just current name */
            add_field("creator[].$last.type", "Person")
        end
        if any_equal("name.type","corporate")
            add_field("creator[].$last.type", "Organization")
        end
    end
end
```

=>
```
  "creator" : [ {
    "name" : "Armbruster, André",
    "type" : "Person"
  }, {
    "name" : "Seyfert, Robert",
    "type" : "Person"
  } ]
```
_________without `set_array`[ See example here in Playground.](https://test.metafacture.org/playground/?data=&flux=%22https%3A//gitlab.com/oersi/oersi-etl/-/raw/metafix/data/experimental/duepub-metafacture.xml%22%0A%7C+open-http%0A%7C+decode-xml%0A%7C+handle-generic-xml%28emitNamespace%3D%22true%22%29%0A%7C+fix%0A%7C+encode-json%28prettyPrinting%3D%22true%22%29%0A%7C+print%0A%3B&fix=if+any_equal+%28%22header.status%22%2C+%22deleted%22%29%0A++++reject%28%29%0Aend%0A%0A%0A/%2A+TODO%3A+learningResourceType+%2A/%0A%0Ado+list%28%22path%22%3A%22metadata.mods%3Amods.mods%3Agenre%22%2C%22var%22%3A%22lRT%22%29%0A++++if+any_match%28%22lRT.authorityURI%22%2C%22https%3A//duepublico.uni-due.de/api/v1/classifications/mir_genres%22%29%0A++++++++copy_field%28%22lRT.valueURI%22%2C%22learningResourceType%5B%5D.%24append.id%22%29+%0A++++++++copy_field%28%22lRT.valueURI%22%2C%22learningResourceType%5B%5D.%24last.prefLabel.de%22%29%0A++++end%0Aend%0A%0Aretain%28%22learningResourceType%5B%5D%22%29&morph=&active-editor=fix)
```
`/* TODO: learningResourceType */
# TODO: Needs lookup but array behaviour some not to work here.
do list("path":"metadata.mods:mods.mods:genre","var":"lRT")
    if any_match("lRT.authorityURI","https://duepublico.uni-due.de/api/v1/classifications/mir_genres") /* TODO: looks at all, not just current */
        copy_field("lRT.valueURI","learningResourceType[].$append.id") #???
        copy_field("lRT.valueURI","learningResourceType[].$last.prefLabel.de") /* TODO: we only get the very last, not every last one */
    end
end
```
=>
```
  "learningResourceType" : [ "https://duepublico.uni-due.de/api/v1/classifications/mir_genres#audio", {
    "de" : "https://duepublico.uni-due.de/api/v1/classifications/mir_genres#audio"
  } ],
```

**Comment by TobiasNx** [comment]
Without `set_array` it seems to handle newly created arrays as list of values but not of objects.


_______with` set_array`

```
#  ------------creator------------------------------------
set_array("creator[]")
do list("path":"metadata.mods:mods.mods:name","var":"name")
    if any_match("name.mods:role.mods:roleTerm.*.value","aut|cre")
        copy_field("name.mods:displayForm.value","creator[].$append.name")
        /* This seems not to work */
        if any_equal("name.type","personal") /* TODO: looks at all names, not just current name */
            add_field("creator[].$last.type", "Person")
        end
        if any_equal("name.type","corporate")
            add_field("creator[].$last.type", "Organization")
        end
    end
```

=>
```
  "creator" : [ {
    "name" : "Armbruster, André",
    "type" : "Person"
  }, {
    "name" : "Seyfert, Robert",
    "type" : "Person"
  } ]
```
_________without `set_array`
```
`/* TODO: learningResourceType */
# TODO: Needs lookup but array behaviour some not to work here.
do list("path":"metadata.mods:mods.mods:genre","var":"lRT")
    if any_match("lRT.authorityURI","https://duepublico.uni-due.de/api/v1/classifications/mir_genres") /* TODO: looks at all, not just current */
        copy_field("lRT.valueURI","learningResourceType[].$append.id") #???
        copy_field("lRT.valueURI","learningResourceType[].$last.prefLabel.de") /* TODO: we only get the very last, not every last one */
    end
```
=>
```
  "learningResourceType" : [ "https://duepublico.uni-due.de/api/v1/classifications/mir_genres#audio", {
    "de" : "https://duepublico.uni-due.de/api/v1/classifications/mir_genres#audio"
  } ],
```

or here without `set_array` with an bad workaround 
```
copy_field("metadata.mods:mods.mods:language.mods:languageTerm.value","inLanguage[].$append.label")

```

=>
`
  "inLanguage" : [ "de" ],`

**Comment by TobiasNx** [comment]
It seems that the "workaround" nor the direct way with `create_field` is working with arrays of strings
```

#  ------------inLanguage------------------------------------
set_array("inLanguage[]")
copy_field("metadata.mods:mods.mods:language.mods:languageTerm.value","inLanguage[].$append")
```
breaks the process.

it only works if you use `copy_field` and add a  subfield. see example above.

copy_field("metadata.mods:mods.mods:language.mods:languageTerm.value","inLanguage[].$append.label")

This hints perhaps an error for another ticket: you only can refrence/target subfields of objects in an array but you cannot do that with an string in an list of strings.

**Comment by TobiasNx** [comment]
I added playground examples to better illustrate the errors.

**Comment by TobiasNx** [comment]
An workaround with set_array is only working if there at least on instance of the subfield is expected otherwise an emtpy array will appear.  `vacuum()` does not recognize empty arrays this does not help to:
[See here](https://test.metafacture.org/playground/?data=&flux=%22https%3A//gitlab.com/oersi/oersi-etl/-/raw/metafix/data/experimental/duepub-metafacture.xml%22%0A%7C+open-http%0A%7C+decode-xml%0A%7C+handle-generic-xml%28emitNamespace%3D%22true%22%29%0A%7C+fix%0A%7C+encode-json%28prettyPrinting%3D%22true%22%29%0A%7C+print%0A%3B&fix=if+any_equal+%28%22header.status%22%2C+%22deleted%22%29%0A++++reject%28%29%0Aend%0A%0A%0A/%2A+TODO%3A+learningResourceType+%2A/%0A/%2A+TODO%3A+contributor+%2A/%0Aset_array%28%22contributor%5B%5D%22%29%0Ado+list%28%22path%22%3A%22metadata.mods%3Amods.mods%3Aname%22%2C%22var%22%3A%22contributor%22%29%0A++++if+any_match%28%22name.mods%3Arole.mods%3AroleTerm.%2A.value%22%2C%22test%22%29%0A++++++++copy_field%28%22contributor.displayForm.value%22%2C%22contributor%5B%5D.%24append.name%22%29%0A++++end%0Aend%0A%0Aretain%28%22contributor%5B%5D%22%29%0Avacuum%28%29&morph=&active-editor=fix)

**Comment by fsteeg** [comment]
> It seems that the "workaround" nor the direct way with create_field is working with arrays of strings

The samples from https://github.com/metafacture/metafacture-fix/issues/80#issuecomment-982751921 seem to be fixed with #82, both look good: [w/ set_array](https://test.metafacture.org/playground/?data=1%7Ba%3A+Faust%2C+b+%7Bn%3A+Goethe%2C+v%3A+JW%7D%2C+c%3A+Weimar%7D%0A2%7Ba%3A+R%C3%A4uber%2C+b+%7Bn%3A+Schiller%2C+v%3A+F%7D%2C+c%3A+Weimar%7D&flux=%22https%3A//gitlab.com/oersi/oersi-etl/-/raw/metafix/data/experimental/duepub-metafacture.xml%22%0A%7C+open-http%0A%7C+decode-xml%0A%7C+handle-generic-xml%28emitNamespace%3D%22true%22%29%0A%7C+fix%0A%7C+encode-json%0A%7C+print%0A%3B&fix=if+any_equal+%28%22header.status%22%2C+%22deleted%22%29%0A++++reject%28%29%0Aend%0A%0Aset_array%28%22inLanguage%5B%5D%22%29%0Acopy_field%28%22metadata.mods%3Amods.mods%3Alanguage.mods%3AlanguageTerm.value%22%2C%22inLanguage%5B%5D.%24append%22%29%0A%0Aretain%28%22inLanguage%5B%5D%22%29&morph=%3C%3Fxml+version%3D%221.0%22+encoding%3D%22UTF-8%22%3F%3E%0A%3Cmetamorph+xmlns%3D%22http%3A//www.culturegraph.org/metamorph%22+xmlns%3Axsi%3D%22http%3A//www.w3.org/2001/XMLSchema-instance%22%0A%09version%3D%221%22%3E%0A%09%3Crules%3E%0A%09%09%3Cdata+source%3D%22_id%22+name%3D%22id%22/%3E%0A%09%09%3Cdata+source%3D%22a%22+name%3D%22title%22/%3E%0A%09%09%3Ccombine+value%3D%22%24%7Bfirst%7D+%24%7Blast%7D+aus+%24%7Bplace%7D%22+name%3D%22author%22%3E%0A%09%09%09%3Cdata+source%3D%22b.v%22+name%3D%22first%22+/%3E%0A%09%09%09%3Cdata+source%3D%22b.n%22+name%3D%22last%22+/%3E%0A%09%09%09%3Cdata+source%3D%22c%22+name%3D%22place%22+/%3E%0A%09%09%3C/combine%3E%0A%09%3C/rules%3E%0A%3C/metamorph%3E%0A&active-editor=fix), [w/o set_array](https://test.metafacture.org/playground/?data=1%7Ba%3A+Faust%2C+b+%7Bn%3A+Goethe%2C+v%3A+JW%7D%2C+c%3A+Weimar%7D%0A2%7Ba%3A+R%C3%A4uber%2C+b+%7Bn%3A+Schiller%2C+v%3A+F%7D%2C+c%3A+Weimar%7D&flux=%22https%3A//gitlab.com/oersi/oersi-etl/-/raw/metafix/data/experimental/duepub-metafacture.xml%22%0A%7C+open-http%0A%7C+decode-xml%0A%7C+handle-generic-xml%28emitNamespace%3D%22true%22%29%0A%7C+fix%0A%7C+encode-json%0A%7C+print%0A%3B&fix=if+any_equal+%28%22header.status%22%2C+%22deleted%22%29%0A++++reject%28%29%0Aend%0A%0Acopy_field%28%22metadata.mods%3Amods.mods%3Alanguage.mods%3AlanguageTerm.value%22%2C%22inLanguage%5B%5D.%24append%22%29%0A%0Aretain%28%22inLanguage%5B%5D%22%29&morph=%3C%3Fxml+version%3D%221.0%22+encoding%3D%22UTF-8%22%3F%3E%0A%3Cmetamorph+xmlns%3D%22http%3A//www.culturegraph.org/metamorph%22+xmlns%3Axsi%3D%22http%3A//www.w3.org/2001/XMLSchema-instance%22%0A%09version%3D%221%22%3E%0A%09%3Crules%3E%0A%09%09%3Cdata+source%3D%22_id%22+name%3D%22id%22/%3E%0A%09%09%3Cdata+source%3D%22a%22+name%3D%22title%22/%3E%0A%09%09%3Ccombine+value%3D%22%24%7Bfirst%7D+%24%7Blast%7D+aus+%24%7Bplace%7D%22+name%3D%22author%22%3E%0A%09%09%09%3Cdata+source%3D%22b.v%22+name%3D%22first%22+/%3E%0A%09%09%09%3Cdata+source%3D%22b.n%22+name%3D%22last%22+/%3E%0A%09%09%09%3Cdata+source%3D%22c%22+name%3D%22place%22+/%3E%0A%09%09%3C/combine%3E%0A%09%3C/rules%3E%0A%3C/metamorph%3E%0A&active-editor=fix).

> An workaround with set_array is only working if there at least on instance of the subfield is expected otherwise an emtpy array will appear.

Tweaked [your sample](https://test.metafacture.org/playground/?data=&flux=%22https%3A//gitlab.com/oersi/oersi-etl/-/raw/metafix/data/experimental/duepub-metafacture.xml%22%0A%7C+open-http%0A%7C+decode-xml%0A%7C+handle-generic-xml%28emitNamespace%3D%22true%22%29%0A%7C+fix%0A%7C+encode-json%28prettyPrinting%3D%22true%22%29%0A%7C+print%0A%3B&fix=if+any_equal+%28%22header.status%22%2C+%22deleted%22%29%0A++++reject%28%29%0Aend%0A%0A%0A/%2A+TODO%3A+learningResourceType+%2A/%0A/%2A+TODO%3A+contributor+%2A/%0Aset_array%28%22contributor%5B%5D%22%29%0Ado+list%28%22path%22%3A%22metadata.mods%3Amods.mods%3Aname%22%2C%22var%22%3A%22contributor%22%29%0A++++if+any_match%28%22name.mods%3Arole.mods%3AroleTerm.%2A.value%22%2C%22test%22%29%0A++++++++copy_field%28%22contributor.displayForm.value%22%2C%22contributor%5B%5D.%24append.name%22%29%0A++++end%0Aend%0A%0Aretain%28%22contributor%5B%5D%22%29%0Avacuum%28%29&morph=&active-editor=fix): remove if-conditional and add 'mods' namespace to 'displayForm': [looks good](https://test.metafacture.org/playground/?data=&flux=%22https%3A//gitlab.com/oersi/oersi-etl/-/raw/metafix/data/experimental/duepub-metafacture.xml%22%0A%7C+open-http%0A%7C+decode-xml%0A%7C+handle-generic-xml%28emitNamespace%3D%22true%22%29%0A%7C+fix%0A%7C+encode-json%28prettyPrinting%3D%22true%22%29%0A%7C+print%0A%3B&fix=if+any_equal+%28%22header.status%22%2C+%22deleted%22%29%0A++++reject%28%29%0Aend%0A%0A%0A/%2A+TODO%3A+learningResourceType+%2A/%0A/%2A+TODO%3A+contributor+%2A/%0Aset_array%28%22contributor%5B%5D%22%29%0Ado+list%28%22path%22%3A%22metadata.mods%3Amods.mods%3Aname%22%2C%22var%22%3A%22contributor%22%29%0A++++copy_field%28%22contributor.mods%3AdisplayForm.value%22%2C%22contributor%5B%5D.%24append.name%22%29%0Aend%0A%0Aretain%28%22contributor%5B%5D%22%29%0Avacuum%28%29&morph=&active-editor=fix).

(In general issue examples should point to the production playground, not test, so we can easily compare them in review).

We're certainly not done with the `set_array` behavior, but since we're leaving #65 open for inconsistencies in array handling, and since for practical purposes, `set_array` now seems to work, maybe we can close this issue here?

**Comment by TobiasNx** [comment]
Great! +1

> > An workaround with set_array is only working if there at least on instance of the subfield is expected otherwise an emtpy array will appear.
> 
> Tweaked [your sample](https://test.metafacture.org/playground/?data=&flux=%22https%3A//gitlab.com/oersi/oersi-etl/-/raw/metafix/data/experimental/duepub-metafacture.xml%22%0A%7C+open-http%0A%7C+decode-xml%0A%7C+handle-generic-xml%28emitNamespace%3D%22true%22%29%0A%7C+fix%0A%7C+encode-json%28prettyPrinting%3D%22true%22%29%0A%7C+print%0A%3B&fix=if+any_equal+%28%22header.status%22%2C+%22deleted%22%29%0A++++reject%28%29%0Aend%0A%0A%0A/%2A+TODO%3A+learningResourceType+%2A/%0A/%2A+TODO%3A+contributor+%2A/%0Aset_array%28%22contributor%5B%5D%22%29%0Ado+list%28%22path%22%3A%22metadata.mods%3Amods.mods%3Aname%22%2C%22var%22%3A%22contributor%22%29%0A++++if+any_match%28%22name.mods%3Arole.mods%3AroleTerm.%2A.value%22%2C%22test%22%29%0A++++++++copy_field%28%22contributor.displayForm.value%22%2C%22contributor%5B%5D.%24append.name%22%29%0A++++end%0Aend%0A%0Aretain%28%22contributor%5B%5D%22%29%0Avacuum%28%29&morph=&active-editor=fix): remove if-conditional and add 'mods' namespace to 'displayForm': [looks good](https://test.metafacture.org/playground/?data=&flux=%22https%3A//gitlab.com/oersi/oersi-etl/-/raw/metafix/data/experimental/duepub-metafacture.xml%22%0A%7C+open-http%0A%7C+decode-xml%0A%7C+handle-generic-xml%28emitNamespace%3D%22true%22%29%0A%7C+fix%0A%7C+encode-json%28prettyPrinting%3D%22true%22%29%0A%7C+print%0A%3B&fix=if+any_equal+%28%22header.status%22%2C+%22deleted%22%29%0A++++reject%28%29%0Aend%0A%0A%0A/%2A+TODO%3A+learningResourceType+%2A/%0A/%2A+TODO%3A+contributor+%2A/%0Aset_array%28%22contributor%5B%5D%22%29%0Ado+list%28%22path%22%3A%22metadata.mods%3Amods.mods%3Aname%22%2C%22var%22%3A%22contributor%22%29%0A++++copy_field%28%22contributor.mods%3AdisplayForm.value%22%2C%22contributor%5B%5D.%24append.name%22%29%0Aend%0A%0Aretain%28%22contributor%5B%5D%22%29%0Avacuum%28%29&morph=&active-editor=fix).
> 
> (In general issue examples should point to the production playground, not test, so we can easily compare them in review).

I think the error was intentiona or at least the result was right :Dl. To show that vacuum() does not help with empty arrays and this is a problem for the . This should be a new ticket.


> We're certainly not done with the `set_array` behavior, but since we're leaving #65 open for inconsistencies in array handling, and since for practical purposes, `set_array` now seems to work, maybe we can close this issue here?
+1

**Comment by TobiasNx** [comment]
wait i spottet the following for working without` set_array`:

https://test.metafacture.org/playground/?data=&flux=%22https%3A//gitlab.com/oersi/oersi-etl/-/raw/metafix/data/experimental/duepub-metafacture.xml%22%0A%7C+open-http%0A%7C+decode-xml%0A%7C+handle-generic-xml%28emitNamespace%3D%22true%22%29%0A%7C+fix%0A%7C+encode-json%28prettyPrinting%3D%22true%22%29%0A%7C+print%0A%3B&fix=if+any_equal+%28%22header.status%22%2C+%22deleted%22%29%0A++++reject%28%29%0Aend%0A%0A%0Ado+list%28%22path%22%3A%22metadata.mods%3Amods.mods%3Aname%22%2C%22var%22%3A%22contributor%22%29%0A++++copy_field%28%22contributor.mods%3AdisplayForm.value%22%2C%22contributor%5B%5D.%24append.name%22%29%0Aend%0A%0Aretain%28%22contributor%5B%5D%22%29%0Avacuum%28%29&morph=&active-editor=fix

**Comment by fsteeg** [comment]
> wait i spottet the following for working without set_array

Fixed with related changes from #82 / #87: [issue on prod](https://metafacture.org/playground/?data=&flux=%22https%3A//gitlab.com/oersi/oersi-etl/-/raw/metafix/data/experimental/duepub-metafacture.xml%22%0A%7C+open-http%0A%7C+decode-xml%0A%7C+handle-generic-xml%28emitNamespace%3D%22true%22%29%0A%7C+fix%0A%7C+encode-json%28prettyPrinting%3D%22true%22%29%0A%7C+print%0A%3B&fix=if+any_equal+%28%22header.status%22%2C+%22deleted%22%29%0A++++reject%28%29%0Aend%0A%0A%0Ado+list%28%22path%22%3A%22metadata.mods%3Amods.mods%3Aname%22%2C%22var%22%3A%22contributor%22%29%0A++++copy_field%28%22contributor.mods%3AdisplayForm.value%22%2C%22contributor%5B%5D.%24append.name%22%29%0Aend%0A%0Aretain%28%22contributor%5B%5D%22%29%0Avacuum%28%29&morph=&active-editor=fix), [fixed on test](https://test.metafacture.org/playground/?data=&flux=%22https%3A//gitlab.com/oersi/oersi-etl/-/raw/metafix/data/experimental/duepub-metafacture.xml%22%0A%7C+open-http%0A%7C+decode-xml%0A%7C+handle-generic-xml%28emitNamespace%3D%22true%22%29%0A%7C+fix%0A%7C+encode-json%28prettyPrinting%3D%22true%22%29%0A%7C+print%0A%3B&fix=if+any_equal+%28%22header.status%22%2C+%22deleted%22%29%0A++++reject%28%29%0Aend%0A%0A%0Ado+list%28%22path%22%3A%22metadata.mods%3Amods.mods%3Aname%22%2C%22var%22%3A%22contributor%22%29%0A++++copy_field%28%22contributor.mods%3AdisplayForm.value%22%2C%22contributor%5B%5D.%24append.name%22%29%0Aend%0A%0Aretain%28%22contributor%5B%5D%22%29%0Avacuum%28%29&morph=&active-editor=%3Afix).

**Comment by blackwinter** [comment]
@TobiasNx: Can you assign me when #87 is ready to be merged?

**Comment by TobiasNx** [comment]
I wait for fix of #87 to review this again.

**Comment by fsteeg** [comment]
I don't understand, still looks good to me, as linked in https://github.com/metafacture/metafacture-fix/issues/80#issuecomment-989706780:

[issue on prod](https://metafacture.org/playground/?data=&flux=%22https%3A//gitlab.com/oersi/oersi-etl/-/raw/metafix/data/experimental/duepub-metafacture.xml%22%0A%7C+open-http%0A%7C+decode-xml%0A%7C+handle-generic-xml%28emitNamespace%3D%22true%22%29%0A%7C+fix%0A%7C+encode-json%28prettyPrinting%3D%22true%22%29%0A%7C+print%0A%3B&fix=if+any_equal+%28%22header.status%22%2C+%22deleted%22%29%0A++++reject%28%29%0Aend%0A%0A%0Ado+list%28%22path%22%3A%22metadata.mods%3Amods.mods%3Aname%22%2C%22var%22%3A%22contributor%22%29%0A++++copy_field%28%22contributor.mods%3AdisplayForm.value%22%2C%22contributor%5B%5D.%24append.name%22%29%0Aend%0A%0Aretain%28%22contributor%5B%5D%22%29%0Avacuum%28%29&morph=&active-editor=fix)

```
{
  "contributor" : [ {
    "1" : "Armbruster, André",
    "2" : "Seyfert, Robert"
  } ]
}
{
  "contributor" : [ "Oeste, Bettina" ]
}
```

[fixed on test](https://test.metafacture.org/playground/?data=&flux=%22https%3A//gitlab.com/oersi/oersi-etl/-/raw/metafix/data/experimental/duepub-metafacture.xml%22%0A%7C+open-http%0A%7C+decode-xml%0A%7C+handle-generic-xml%28emitNamespace%3D%22true%22%29%0A%7C+fix%0A%7C+encode-json%28prettyPrinting%3D%22true%22%29%0A%7C+print%0A%3B&fix=if+any_equal+%28%22header.status%22%2C+%22deleted%22%29%0A++++reject%28%29%0Aend%0A%0A%0Ado+list%28%22path%22%3A%22metadata.mods%3Amods.mods%3Aname%22%2C%22var%22%3A%22contributor%22%29%0A++++copy_field%28%22contributor.mods%3AdisplayForm.value%22%2C%22contributor%5B%5D.%24append.name%22%29%0Aend%0A%0Aretain%28%22contributor%5B%5D%22%29%0Avacuum%28%29&morph=&active-editor=%3Afix)

```
{
  "contributor" : [ {
    "name" : "Armbruster, André"
  }, {
    "name" : "Seyfert, Robert"
  } ]
}
{
  "contributor" : [ {
    "name" : "Oeste, Bettina"
  } ]
}
```

**Comment by TobiasNx** [comment]
I set this on hold, because of the combined PR for this and the other ticket #82.

Adding and copying sub-fields seem to work. What seems not to work is copying and moving objects into an array:
https://github.com/oersi/oersi-etl/blob/2a05f299ebb6346cf59b4d1ad7b8930531a9a834/data/experimental/appendArrays/test_append_object.flux

[See here in the Playground too](
https://test.metafacture.org/playground/?data=%7B%0A%09%22animals%22%3A%5B%0A%09%09%09%7B%22animal%22%3A+%22dog%22%7D%2C%0A%09%09%09%7B%22animal%22%3A+%22cat%22%7D%0A%09%5D%2C%0A%09%22others%22%3A+%7B%22animal%22%3A+%22human%22%7D%2C%0A%09%22fictional%22%3A+%7B%22animal%22%3A+%22unicorn%22%7D%0A%7D&flux=PG_DATA%0A%7C+as-records%0A%7C+decode-json%0A%7C+fix%0A%7C+encode-json%28prettyPrinting%3D%22true%22%29%0A%7C+print%0A%3B&fix=copy_field%28%22others%22%2C+%22animals%5B%5D.%24append%22%29%0A%0Amove_field%28%22fictional%22%2C+%22animals%5B%5D.%24append%22%29%0A%0Aadd_field%28%22animals%5B%5D.%24append.animal%22%2C+%22earthworm%22%29&morph=&active-editor=fix)

This might be a separate ticket though.

**Comment by fsteeg** [comment]
> This might be a separate ticket though.

Right, what's missing here is `$append` support for objects in move_field and copy_field. We can still discuss if we need this now in #87, or later. But this issue here seems no longer related at this point.

**Comment by TobiasNx** [comment]
PS: From the original tests it seems that `$last`is not working anymore. Also should be dealt with in another ticket.
